version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: jero
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: geography_db
    ports:
      - '5433:5432'
    volumes:
      - geography_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U jero -d geography_db']
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      DATABASE_URL: postgresql://jero:123@postgres:5432/geography_db
      NODE_ENV: development
      PORT: 3000
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  geography_data: