apiVersion: v1
kind: Service
metadata:
  name: geography-api
  namespace: geography-api
  labels:
    app: geography-api
spec:
  # 
  # .
  type: LoadBalancer
  selector:
    app: geography-api
  ports:
    - name: http
      port: 80
      targetPort: 3000
      protocol: TCP
